### ISSUE TITLE
extra parenthesis

### ISSUE THREAD

**Issue by kamelNaroun** [erwanp/pytexit#13] opened 2020-05-04 14:21 UTC
Hello,
I don't know if that issue is connected to the new version of Python3.8 but when I try
py2tex('2+3'), I have an output with extra parenthesis.

`$ python
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytexit import py2tex
>>> py2tex('2+3')
$$\left(2\right)+\left(3\right)$$
'$$\\left(2\\right)+\\left(3\\right)$$'`

**Comment by kamelNaroun** [comment] 2020-05-04 16:09
I have read in the ast module documentation that the ast.Num class is deprecated and I have understood that it is replaced by ast.Constant class.

**Comment by erwanp** [comment] 2020-05-13 19:26
Thank you for reporting this ! Do you have an idea on how to fix that ?

**Comment by kamelNaroun** [comment] 2020-05-18 07:02
No for the moment. I may think of that later.

**Comment by phidi04** [comment] 2021-01-29 10:14
Can't reproduce this, seems to be fixed by now.

>>> from pytexit import py2tex
>>> py2tex('2+3')
>>> $$2+3$$
>>> '$$2+3$$'

**Comment by erwanp** [comment] 2021-01-29 11:55
Probably with #16. 

Thanks for checking, closing !

**Closed by erwanp** 2021-01-29 11:55 UTC
Labels: good first issue
